# Generated by Django 5.1.7 on 2025-03-28 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_userprofile_password_userprofile_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=15)),
                ('timing', models.CharField(max_length=100)),
                ('charges', models.DecimalField(decimal_places=2, max_digits=10)),
                ('availability', models.BooleanField(default=True, null=True)),
            ],
        ),
    ]
