# Generated by Django 5.1.7 on 2025-03-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_servicelisting'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicelisting',
            name='booking',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='servicelisting',
            name='availability',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
