# Generated by Django 5.1.7 on 2025-03-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_servicelisting_booking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicelisting',
            name='customer',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
