# Generated by Django 5.1.7 on 2025-03-29 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_servicelisting_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='serviceProvider',
            field=models.BooleanField(default=False),
        ),
    ]
