# Generated by Django 5.1.7 on 2025-03-29 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_userprofile_serviceprovider'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicelisting',
            name='confirmation',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
