# Generated by Django 5.1.7 on 2025-03-30 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_servicelisting_confirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicelisting',
            name='url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
