# Generated by Django 5.1.7 on 2025-03-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_servicelisting_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicelisting',
            name='url',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
